# Generated by Django 5.2.3 on 2025-06-11 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['nome'],
            },
        ),
    ]
